import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/about.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function home(){
    return(
        <>
            <Head>
                <title>POOH</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/smile.png" />
            </Head>

            <main >
                <div className={`${styles.ehe}`}>
                    <nav className={`${styles.nav}`}>
                    <Link href={"/"}>
                    <div className={`${styles.logo}`}></div>
                    </Link>
                        <div className={`${styles.navi}`}>
                            <Link href={"/"} className={`${styles.links}`}>
                            <div className={`${styles.linknav1}`}>Home</div>
                            </Link>
                            <Link href={"about"} className={`${styles.links}`}>
                            <div className={`${styles.linknav2}`}>About</div>
                            </Link>
                            <Link href={"lab"} className={`${styles.links}`}>
                            <div className={`${styles.linknav3}`}>MyLab</div>
                            </Link>
                        </div>
                    </nav>

                    <div className={`${styles.top}`}>
                        <h1>About Me :)</h1>
                        <p>My name is Poowadech Homhuan. I have over three years of experience to training as a web developer so I can quickly create some standard websites.
My favorites are memes and jokes.
I like to create innovative things. XD
                        </p>
                    </div>
                    <div className={`${styles.verybigblock}`}>


                    <div className={`${styles.bigblock}`}>
                        <div className={`${styles.block}`}></div>
                        <div className={`${styles.blocktext}`}>
                            <h1>
                            Finish High school at SamoengPittayakom school in Science&MathMethic.    
                            </h1>
                        </div>
                    </div>
                    <div className={`${styles.bigblockl}`}>
                        <div className={`${styles.block1}`}></div>
                        <div className={`${styles.blocktext}`}>
                            <h1>
                            2019, Start training at developer. my first project is game from rpg-maker. 
                            </h1>
                        </div>
                    </div>
                    <div className={`${styles.bigblock}`}>
                        <div className={`${styles.block2}`}></div>
                        <div className={`${styles.blocktext}`}>
                            <h1>
                            2020, Learning Computer-science at Maejo University.
                            first team project is Jarskin-website.
                            </h1>
                        </div>
                    </div>
                    <div className={`${styles.bigblock}`}>
                        <div className={`${styles.block6}`}></div>
                        <div className={`${styles.blocktext}`}>
                            <h1>
                            2020, first team project is Jarskin-website.
                            </h1>
                        </div>
                    </div>
                    <div className={`${styles.bigblockl}`}>
                        <div className={`${styles.block5}`}></div>
                        <div className={`${styles.blocktext}`}>
                            <h1>
                            2021, create Fortune telling Application with AndriodStudio.
                            </h1>
                        </div>
                    </div>
                    <div className={`${styles.bigblockl}`}>
                        <div className={`${styles.block3}`}></div>
                        <div className={`${styles.blocktext}`}>
                            <h1>
                            2021, create Kopcareon website project.
                            </h1>
                        </div>
                    </div>
                    <div className={`${styles.bigblock}`}>
                        <div className={`${styles.block4}`}></div>
                        <div className={`${styles.blocktext}`}>
                            <h1>
                            2022, Make game with Roblox Studio. 
                            (MydeerObby)  
                            </h1>
                        </div>
                    </div>
                    <div className={`${styles.bigblock}`}>
                        <div className={`${styles.block7}`}></div>
                        <div className={`${styles.blocktext}`}>
                            <h1>
                            2022, Create website for MydeerObby game.
                            </h1>
                        </div>
                    </div>
                    </div>


                    <div className={`${styles.yeet}`}></div>

                </div>
            </main>
        
        </>
    );

}