import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/indexs.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>POOH</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/smile.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={`${styles.ehe}`}>
        <nav className={`${styles.nav}`}>
                    <Link href={"/"}>
                    <div className={`${styles.logo}`}></div>
                    </Link>
                        <div className={`${styles.navi}`}>
                            <Link href={"/"} className={`${styles.links}`}>
                            <div className={`${styles.linknav1}`}>Home</div>
                            </Link>
                            <Link href={"about"} className={`${styles.links}`}>
                            <div className={`${styles.linknav2}`}>About</div>
                            </Link>
                            <Link href={"lab"} className={`${styles.links}`}>
                            <div className={`${styles.linknav3}`}>MyLab</div>
                            </Link>
                        </div>
          </nav>

          <div className={`${styles.topic}`}>
            <h1>Poowadech Portfolio ☺</h1>
            <div className={`${styles.block}`}></div>
          </div>
          <div className={`${styles.desc}`}>
            <p className={`${styles.gr}`}>Welcome!♫♪</p>
            <p className={`${styles.c3}`}>☻I am Poowadech Homhuan</p>
            <p className={`${styles.c2}`}>☺I am mini developer. </p>
            <p className={`${styles.c1}`}>☻I am looking more dev-experience for create innovative things.
            </p>
            <p className={`${styles.gr2}`}>you can call me Pooh :)</p>
          </div>
          <div className={`${styles.icon}`}>
            <a href="https://www.facebook.com/poowadach.homhuan/" target="_blank" rel="noopener noreferrer">
              <img src="images/fb.png" className={styles.iconpig} />
            </a>
            <a href="https://www.instagram.com/iam.pooh555?igsh=YW16MHYxZjhnbWI4" target="_blank" rel="noopener noreferrer">
              <img src="images/ig.png" className={styles.iconpig2} />
            </a>            
            <a href="https://github.com/Pencil05" target="_blank" rel="noopener noreferrer">
              <img src="images/git.png" className={styles.iconpig3} />
            </a>
          </div>
          <div className={`${styles.gosite}`}>
          <Link href="/" className={`${styles.gosite}`}> 
            <button className="">
              site
            </button>
          </Link>
          </div>

        </div>
      </main>
    </>
  );
}
