import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function home(){
    return(
        <>
            <Head>
            <title>POOH</title>

                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/smile.jpg" />
            </Head>

            <main >
                <div className={`${styles.ehe}`}>
                    <nav className={`${styles.nav}`}>
                    <Link href={"/"}>
                    <div className={`${styles.logo}`}></div>
                    </Link>
                        <div className={`${styles.navi}`}>
                            <Link href={"/"} className={`${styles.links}`}>
                            <div className={`${styles.linknav1}`}>Home</div>
                            </Link>
                            <Link href={"about"} className={`${styles.links}`}>
                            <div className={`${styles.linknav2}`}>About</div>
                            </Link>
                            <Link href={"lab"} className={`${styles.links}`}>
                            <div className={`${styles.linknav3}`}>MyLab</div>
                            </Link>
                        </div>
                    </nav>

                    <div className={`${styles.top}`}>
                        <h1>Pooh's Lab</h1>
                        <p>this is my 
                        performance that you can play</p>
                    </div>

                    <div className={`${styles.bigblock}`}>
                        <Link href={'https://jarskin.netlify.app/'}>
                        <div className={`${styles.block}`}></div>
                        </Link>
                        <Link href={'https://jarskin.netlify.app/'}>
                        <div className={`${styles.block}`}></div>
                        </Link>
                        <Link href={'https://jarskin.netlify.app/'}>
                        <div className={`${styles.block}`}></div>
                        </Link>

                        <Link href={'https://jarskin.netlify.app/'}>
                        <div className={`${styles.block}`}></div>
                        </Link>
                        <Link href={'https://jarskin.netlify.app/'}>
                        <div className={`${styles.block}`}></div>
                        </Link>
                        <Link href={'https://jarskin.netlify.app/'}>
                        <div className={`${styles.block}`}></div>
                        </Link>
                    </div>


                </div>
            </main>
        
        </>
    );

}